#!/usr/bin/env python3
"""Bake Grafana provisioning + dashboard files into base64 env vars for docker-compose.

Compose refactor 2.0 (kanban t_884fec4a) — see docker/entrypoint_grafana.sh.

This script reads the checked-in Grafana provisioning YAMLs and dashboard
JSONs from ``docker/grafana/``, base64-encodes each one, and emits lines
suitable for dropping into a ``.env`` file alongside the rest of the
alphard stack secrets. The encoded lines are the *same* env vars that the
grafana service declares explicitly in its ``environment:`` block (see
docker-compose.yaml) — Portainer standalone does NOT propagate stack-level
Env values into services that don't opt in, so the env must live both in
the .env body AND in the service.environment block.

Why this lives in tools/ (not scripts/) and is invoked manually
---------------------------------------------------------------
The bake is a developer-time action, not a runtime step:

- Source-of-truth dashboard JSON is edited in ``docker/grafana/dashboards/``
  and committed. The bake picks up the latest committed version.
- The output is the ``GRAFANA_PROVISIONING_B64_*`` block in ``.env.example``
  and ``.env``. We do NOT commit ``.env`` (secrets live there); we DO
  commit the regenerated ``.env.example`` placeholder so a fresh checkout
  knows which vars to expect.
- CI does NOT re-run this on every push — the dashboard JSON only changes
  via explicit PR. PRs that touch ``docker/grafana/`` should regenerate
  ``.env.example`` as part of the same PR; this script is idempotent so
  the diff is minimal.

Output
------
A single ``KEY="VALUE"`` block per file, with a leading ``# ----``
comment delimiting the alphard-managed section. Drop into ``.env`` to
ship the values into the grafana container's environment.

Idempotent: running this twice with no source changes produces byte-
identical output.

Exit codes
----------
0 — success
1 — read error (missing source file, encode error)
2 — usage error (bad CLI args)
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Order matters: this is the order of lines in the emitted .env block.
# Operators diff against this order in PRs, so don't shuffle.
SOURCES: list[tuple[str, Path]] = [
    (
        "PROVISIONING_DATASOURCES_YML_B64",
        REPO_ROOT / "docker" / "grafana" / "provisioning" / "datasources" / "prometheus.yml",
    ),
    (
        "PROVISIONING_DASHBOARDS_PROVIDER_YML_B64",
        REPO_ROOT / "docker" / "grafana" / "provisioning" / "dashboards" / "provider.yml",
    ),
    (
        "DASHBOARD_PHASE0_JSON_B64",
        REPO_ROOT / "docker" / "grafana" / "dashboards" / "alphard-phase0.json",
    ),
    (
        "DASHBOARD_PHASE28_JSON_B64",
        REPO_ROOT / "docker" / "grafana" / "dashboards" / "alphard-phase28.json",
    ),
]


def encode_one(path: Path) -> str:
    """Read ``path`` as bytes and return base64-encoded content with no
    embedded newlines and no trailing newline.

    Why no newlines: ``base64 -d`` in entrypoint_grafana.sh reads stdin
    until EOF; an embedded newline would survive into the decoded file
    and corrupt YAML / JSON parsers downstream. Standard Python
    ``base64.b64encode`` produces 76-char line-wrapped output by default
    — we strip with ``.decode().replace("\n", "")`` then re-encode
    bytes-to-str to guarantee a single line.

    Why no trailing newline: same reason — a trailing newline would
    become a trailing newline in the decoded file. Grafana's YAML loader
    tolerates this for some files but the JSON loader is strict;
    alphard-phase28.json parses fine without a trailing newline, and
    the strict path matches the bake's contract.
    """
    raw = path.read_bytes()
    if not raw:
        raise ValueError(f"{path} is empty (would decode to zero bytes)")
    encoded = base64.b64encode(raw).decode("ascii")
    # base64.b64encode already emits no newlines on its own; the replace
    # is defensive (older Python versions had line wrapping in some
    # configurations).
    return encoded.replace("\n", "")


def emit_block() -> str:
    """Encode all sources and return the .env block.

    Reads each source file under ``docker/grafana/`` (see ``SOURCES``),
    base64-encodes it, and emits the ``KEY="VALUE"`` lines that drop
    into a ``.env`` file. Exits non-zero on a missing source so the
    operator notices immediately rather than silently producing a
    half-populated env file (which would surface in production as a
    grafana container restart-loop with empty provisioning).
    """
    lines: list[str] = []
    lines.append("# ---- Grafana provisioning + dashboards (compose refactor 2.0) ----")
    lines.append("# Generated by tools/bake_grafana_env.py from docker/grafana/.")
    lines.append("# Run `python tools/bake_grafana_env.py` to regenerate after editing")
    lines.append("# the source YAML/JSON files. The grafana service entrypoint decodes")
    lines.append("# these into /etc/grafana/provisioning and /var/lib/grafana/dashboards")
    lines.append("# on every container start (see docker/entrypoint_grafana.sh).")
    lines.append("# Why env-baked: bind-mounts to ./docker/grafana/* break on .107 PVE LXC")
    lines.append("# (userns-mapped nobody owns the leaf, grafana can't read its own")
    lines.append("# provisioning). See kanban t_884fec4a for the full architecture.")
    for key, path in SOURCES:
        if not path.exists():
            print(f"ERROR: source file missing: {path}", file=sys.stderr)
            sys.exit(1)
        encoded = encode_one(path)
        # Wrap value in double quotes for shell-safety; base64 alphabet
        # is alphanumeric + '/' '+' '=' so no special chars, but quotes
        # prevent issues if a future encode scheme includes punctuation.
        lines.append(f'{key}="{encoded}"')
    lines.append("# ---- end Grafana provisioning ----")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Bake Grafana provisioning + dashboards into base64 env vars.",
        epilog="Outputs a .env block; pipe to .env or .env.example as needed.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any source file is missing or empty (CI mode)",
    )
    args = parser.parse_args(argv)

    if args.check:
        # CI use: verify all sources exist + encode. Non-zero on failure.
        for _key, path in SOURCES:
            if not path.exists():
                print(f"FAIL: missing {path}", file=sys.stderr)
                return 1
            try:
                encode_one(path)
            except Exception as e:
                print(f"FAIL: encode error for {path}: {e}", file=sys.stderr)
                return 1
        print("OK: all 4 sources encode cleanly", file=sys.stderr)
        return 0

    block = emit_block()
    sys.stdout.write(block)
    if not block.endswith("\n"):
        sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
